const nullimg="https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/temporary-image.png?alt=media&token=9a903ec7-2bc8-4d62-8a3b-2db8b1c1082a";

const dwData=[
    {
        imgloc:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Training%20sub%20page%2Fdrone%20workshop%2FDronedayimg.jpg?alt=media&token=d7a89b2b-4b17-4dab-ada1-c5f672824d84",
        heading:"3-Days Workshop on Drone",
        day1heading:"Day 1: Introduction to Drone and Basic Concepts",
        session1heading:"Session 1:Introduction to Drone",
        point1:"Overview of the workshop agenda",
        point2:"Types of drones and their history",
        point3:"Applications of drones in various industries",
        session2heading:"Session 2: Drone Components and Technology",
        point4:"Overview of drone hardware (frames, motors, propellers, etc.)",
        point5:"Introduction to drone software and control systems",
        point6:"Understanding sensors and communication systems",
        day2heading:" Day 2: Hands-on Drone Assembly and Flight Basics",
        session3heading:"Session 1: Basic Drone Assembly and Safety",
        point7:"Participants get the opportunity to assemble a basic drone.",
        point8:"Importance of responsible drone operation",
        point9:"Risk management and pre-flight checklists",
        point10:"Hands-on exercises with simulator software for drone control practice",
        session4heading:"Session 2: Outdoor Flight Training",
        point11:"Practical flight demonstrations",
        point12:"Participants get hands-on experience flying drones under supervision.",
        point13:"Autonomous flight modes and features",
        day3heading:" Day 3: Real-world Applications and Future Trends",
        session5heading:"Session 1: Drone Applications in Various Industries",
        point14:"Case studies on how drones are used in agriculture, surveying, filmmaking, etc.",
        point15:"Guest speakers from relevant industries sharing their experiences.",
        point16:"Drone Data Collection and Analysis",
        session6heading:"Session 2: Project Work and Closing",
        point17:"Discussion on the future role of drones in society",
        point18:"About Drone Training Program & Eligibility",
        point19:"Participants work on a small drone-related project.",
        point20:"Presentations and discussions on the projects.",
        point21:"Closing ceremony, certificates, and feedback collection.",
        img1:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Training%20sub%20page%2Fdrone%20workshop%2FDrone%20component.png?alt=media&token=860d30aa-050e-4a6f-88fe-acf43d2d39e8",
        img2:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Training%20sub%20page%2Fdrone%20workshop%2Fcomponent%20img%202.jpg?alt=media&token=b4e60062-c684-4b3f-88f8-5d1429ec2a58",
        img3:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Training%20sub%20page%2Fdrone%20workshop%2Ftraining-image%201.jpg?alt=media&token=cada5cb7-0189-4f33-a92e-1c578ed869f6",
        img4:nullimg,
        title1:"text ?",
        title2:"text ?",
        title3:"text ?",
        title4:"text ?",
    },
]

export default dwData;