const nullimg = "https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/temporary-image.png?alt=media&token=9a903ec7-2bc8-4d62-8a3b-2db8b1c1082a";


const sData=[
    {
        imgloc: "https://static.vecteezy.com/system/resources/previews/005/992/359/non_2x/smart-farming-use-drone-technologies-in-farm-industry-for-plants-growing-wind-mills-solar-panels-and-water-in-flat-cartoon-background-illustration-vector.jpg",
        heading: "Agriculture Drone Applications",
        point1:"Precision Drones",
        point2:"Reliable Solutions",
        point3:"Competitive Rates ",
        point4:"Thriving Fields",
        point5:"Complimentary Service",
        point6:"20-25 acres can be sprayed per day, which is 30 times more than the traditional knapsack sprayer.",
        point7:"90% water can be saved in comparison to traditional spraying methods.",
        point8:"Agriculture drones have a long productive lifespan, low maintenance cost, and their parts are easy to replace as and when required.",
        point9:"Spraying 1 acre of land in 7-10 minutes.",
        point10:"Suitable for spraying on sugarcane and gardens like mango, apple, and banana.",
        point11:"Optimize the use of inputs (seeds, fertilizers, pesticide spraying) on the crop, leading to increased productivity through uniform distribution.",
        img1:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Services%20sub%20pages%2FAgricultuer%20Drone%20Appliction%2FPush%20image1-1.jpg?alt=media&token=fd01bbbd-b6fd-4c94-aa5a-527f2ccf1078",
        img2:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Services%20sub%20pages%2FAgricultuer%20Drone%20Appliction%2FPush%20image1-3.jpg?alt=media&token=16a0c990-c540-42c4-87e8-1b99b070dd50",
        img3:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Services%20sub%20pages%2FAgricultuer%20Drone%20Appliction%2FPush%20image1-5.jpg?alt=media&token=887aacb3-d3df-495a-ba53-a222a6963646",
        img4:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Services%20sub%20pages%2FAgricultuer%20Drone%20Appliction%2FPush%20image1-4.jpg?alt=media&token=d506e3f4-1cb1-46df-a034-466b933c6d11",
    },
    {
        heading:"Mapping & Servillance",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Aerial Photography & Videography",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Drone Assembly",
        imgloc:nullimg,
        topicheading1:"Gather Components:",
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Drone Testing",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Drone Repair Service",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Testing and Calibration",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
]

export default sData;