const nullimg = "https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/temporary-image.png?alt=media&token=9a903ec7-2bc8-4d62-8a3b-2db8b1c1082a";


const pData=[
    {
        imgloc: "https://static.vecteezy.com/system/resources/previews/005/992/359/non_2x/smart-farming-use-drone-technologies-in-farm-industry-for-plants-growing-wind-mills-solar-panels-and-water-in-flat-cartoon-background-illustration-vector.jpg",
        heading: "Agriculture Drone",
        point1:"Precision Drones",
        point2:"Reliable Solutions",
        point3:"Competitive Rates ",
        point4:"Thriving Fields",
        point5:"Complimentary Service",
        point6:"20-25 acres can be sprayed per day, which is 30 times more than the traditional knapsack sprayer.",
        point7:"90% water can be saved in comparison to traditional spraying methods.",
        point8:"Agriculture drones have a long productive lifespan, low maintenance cost, and their parts are easy to replace as and when required.",
        point9:"Spraying 1 acre of land in 7-10 minutes.",
        point10:"Suitable for spraying on sugarcane and gardens like mango, apple, and banana.",
        point11:"Optimize the use of inputs (seeds, fertilizers, pesticide spraying) on the crop, leading to increased productivity through uniform distribution.",
        img1:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Product%2FWhatsApp%20Image%202024-04-13%20at%2016.32.22_3ace9988.jpg?alt=media&token=935bfa31-0b43-4cb7-af81-4bbe96101131",
        img2:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Product%2FWhatsApp%20Image%202024-04-13%20at%2016.37.19_d6be0975.jpg?alt=media&token=4265d83c-e7b9-44f4-9f97-cebf8e0ffafb",
        img3:"https://firebasestorage.googleapis.com/v0/b/pushpak-drone-viman-pvt-ltd.appspot.com/o/Product%2FWhatsApp%20Image%202024-04-13%20at%2016.49.07_9d3778a6.jpg?alt=media&token=e3e2753b-fcdb-4d62-ab12-153b3d564ac2",
        img4:nullimg,
    },
    {
        heading:"Videography Drone",
        imgloc:nullimg,
        point1:"Videography Drone",
        point2:"Construction and Surveying",
        point3:"News Reporting",
        point4:"Wedding Photography/Videography",
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,

    },
    {
        heading:"Mapping Drone",
        imgloc:nullimg,
        point1:"Precision Mapping",
        point2:"Landscape Survey",
        point3:"Urban Planning",
        point4:"Capturing image/data for real- time monitoring crops.",
        point5:"Delivery of Blood samples/ Medicine.",
        point6:"Flying drones over burned areas can assist in assessing the damage caused by fires, including those occurring in residential and non-residential buildings, as well as wildfires. Such incidents lead to a multitude of health issues, including human and animal fatalities, and substantial economic losses due to structural, equipment, and vegetation damage. Utilizing drone’s aids in verifying insurance claims and facilitates the post-fire assessment and recovery process.",
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Drone Components/Kits",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Customised Object",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Lithography 3D Printing",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"3D Printed Object",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
    {
        heading:"Eductional Tools",
        imgloc:nullimg,
        img1:nullimg,
        img2:nullimg,
        img3:nullimg,
        img4:nullimg,	 
    },
]

export default pData;